class FirmwareService {
  constructor() {
    this.platformTemplates = {
      'esp32': {
        language: 'cpp',
        framework: 'arduino',
        includes: ['WiFi.h', 'Wire.h'],
        setup: this.getESP32Setup(),
        loop: this.getESP32Loop()
      },
      'arduino': {
        language: 'cpp', 
        framework: 'arduino',
        includes: ['Wire.h'],
        setup: this.getArduinoSetup(),
        loop: this.getArduinoLoop()
      },
      'rp2040': {
        language: 'cpp',
        framework: 'arduino',
        includes: ['Wire.h'],
        setup: this.getRP2040Setup(),
        loop: this.getRP2040Loop()
      }
    };
    
    this.sensorLibraries = {
      'BME280': {
        library: 'Adafruit_BME280.h',
        init: 'Adafruit_BME280 bme;',
        setup: 'bme.begin(0x76);',
        read: 'float temperature = bme.readTemperature();'
      },
      'SCD41': {
        library: 'SensirionI2CScd4x.h',
        init: 'SensirionI2CScd4x scd4x;',
        setup: 'scd4x.begin(Wire);',
        read: 'uint16_t co2; scd4x.readMeasurement(co2, temperature, humidity);'
      },
      'MPU6050': {
        library: 'MPU6050.h',
        init: 'MPU6050 mpu;',
        setup: 'mpu.initialize();',
        read: 'int16_t ax, ay, az; mpu.getAcceleration(&ax, &ay, &az);'
      }
    };
    
    this.displayLibraries = {
      'SSD1306': {
        library: 'Adafruit_SSD1306.h',
        init: 'Adafruit_SSD1306 display(128, 64, &Wire, -1);',
        setup: 'display.begin(SSD1306_SWITCHCAPVCC, 0x3C);',
        usage: 'display.clearDisplay(); display.println("Hello"); display.display();'
      }
    };
  }

  async generateScaffold(spec, components) {
    try {
      console.log('💻 Generating firmware scaffold...');
      
      // Detect platform
      const platform = this.detectPlatform(components);
      const template = this.platformTemplates[platform];
      
      if (!template) {
        throw new Error(`Unsupported platform: ${platform}`);
      }
      
      // Generate code files
      const files = [];
      
      // Main firmware file
      const mainCode = this.generateMainCode(spec, components, platform, template);
      files.push({
        name: 'main.cpp',
        content: mainCode,
        type: 'source'
      });
      
      // Configuration header
      const configHeader = this.generateConfigHeader(spec, components);
      files.push({
        name: 'config.h',
        content: configHeader,
        type: 'header'
      });
      
      // Library requirements
      const libraries = this.generateLibraryList(components);
      files.push({
        name: 'libraries.txt',
        content: libraries,
        type: 'documentation'
      });
      
      // Platform configuration
      const platformConfig = this.generatePlatformConfig(platform, spec);
      files.push({
        name: 'platformio.ini',
        content: platformConfig,
        type: 'config'
      });
      
      // README for firmware
      const readme = this.generateFirmwareReadme(spec, platform, components);
      files.push({
        name: 'README.md',
        content: readme,
        type: 'documentation'
      });
      
      const firmware = {
        platform: platform,
        framework: template.framework,
        language: template.language,
        files: files,
        mainCode: mainCode,
        metadata: {
          sensors: components.filter(c => c.component.specs?.type?.includes('sensor')).length,
          displays: components.filter(c => c.component.specs?.type === 'display').length,
          interfaces: this.countInterfaces(components),
          complexity: this.calculateFirmwareComplexity(components)
        }
      };
      
      console.log(`✅ Generated firmware with ${files.length} files for ${platform}`);
      return firmware;
      
    } catch (error) {
      console.error('❌ Firmware generation failed:', error);
      throw new Error(`Firmware generation failed: ${error.message}`);
    }
  }
  
  detectPlatform(components) {
    // Find MCU component
    const mcu = components.find(c => c.component.specs?.type === 'mcu');
    
    if (!mcu) {
      return 'arduino'; // Default fallback
    }
    
    const title = mcu.component.title?.toLowerCase() || '';
    
    if (title.includes('esp32')) {
      return 'esp32';
    } else if (title.includes('rp2040')) {
      return 'rp2040';
    } else if (title.includes('atmega')) {
      return 'arduino';
    }
    
    return 'arduino'; // Default
  }
  
  generateMainCode(spec, components, platform, template) {
    let code = '';
    
    // File header
    code += `/*\n`;
    code += ` * ${spec.purpose || 'Generated Firmware'}\n`;
    code += ` * Platform: ${platform}\n`;
    code += ` * Generated by Tyton Creation Engine\n`;
    code += ` */\n\n`;
    
    // Includes
    const includes = new Set(template.includes);
    
    // Add sensor libraries
    for (const comp of components) {
      const sensorLib = this.getSensorLibrary(comp.component.title);
      if (sensorLib) {
        includes.add(sensorLib.library);
      }
      
      const displayLib = this.getDisplayLibrary(comp.component.title);
      if (displayLib) {
        includes.add(displayLib.library);
      }
    }
    
    for (const include of includes) {
      code += `#include <${include}>\n`;
    }
    
    code += `#include "config.h"\n\n`;
    
    // Global variables and objects
    code += `// Global objects\n`;
    for (const comp of components) {
      const sensorInit = this.getSensorInit(comp.component.title);
      if (sensorInit) {
        code += `${sensorInit}\n`;
      }
      
      const displayInit = this.getDisplayInit(comp.component.title);
      if (displayInit) {
        code += `${displayInit}\n`;
      }
    }
    
    code += `\n// Global variables\n`;
    code += `unsigned long lastSensorRead = 0;\n`;
    code += `const unsigned long SENSOR_INTERVAL = 1000; // ms\n\n`;
    
    // Setup function
    code += `void setup() {\n`;
    code += `  Serial.begin(115200);\n`;
    code += `  Serial.println("Starting ${spec.purpose || 'system'}...");\n\n`;
    
    code += `  // Initialize I2C\n`;
    code += `  Wire.begin();\n\n`;
    
    // Platform-specific setup
    code += template.setup;
    
    // Sensor setup
    for (const comp of components) {
      const sensorSetup = this.getSensorSetup(comp.component.title);
      if (sensorSetup) {
        code += `\n  // Initialize ${comp.component.title}\n`;
        code += `  ${sensorSetup}\n`;
      }
      
      const displaySetup = this.getDisplaySetup(comp.component.title);
      if (displaySetup) {
        code += `\n  // Initialize ${comp.component.title}\n`;
        code += `  ${displaySetup}\n`;
      }
    }
    
    code += `\n  Serial.println("Setup complete!");\n`;
    code += `}\n\n`;
    
    // Loop function
    code += `void loop() {\n`;
    
    // Main loop logic
    code += `  unsigned long currentTime = millis();\n\n`;
    
    code += `  // Read sensors periodically\n`;
    code += `  if (currentTime - lastSensorRead >= SENSOR_INTERVAL) {\n`;
    code += `    readSensors();\n`;
    code += `    lastSensorRead = currentTime;\n`;
    code += `  }\n\n`;
    
    // Platform-specific loop
    code += template.loop;
    
    code += `\n  delay(10); // Small delay for stability\n`;
    code += `}\n\n`;
    
    // Sensor reading function
    code += `void readSensors() {\n`;
    code += `  Serial.println("--- Sensor Reading ---");\n\n`;
    
    for (const comp of components) {
      const sensorRead = this.getSensorRead(comp.component.title);
      if (sensorRead) {
        code += `  // Read ${comp.component.title}\n`;
        code += `  ${sensorRead}\n`;
        code += `  Serial.print("${comp.component.title}: ");\n`;
        code += `  Serial.println(/* sensor value */);\n\n`;
      }
    }
    
    code += `}\n\n`;
    
    // Display update function if display present
    const hasDisplay = components.some(c => c.component.specs?.type === 'display');
    if (hasDisplay) {
      code += `void updateDisplay() {\n`;
      code += `  display.clearDisplay();\n`;
      code += `  display.setTextSize(1);\n`;
      code += `  display.setTextColor(SSD1306_WHITE);\n`;
      code += `  display.setCursor(0, 0);\n`;
      code += `  display.println("${spec.purpose || 'System Status'}");\n`;
      code += `  display.println("");\n`;
      code += `  // Add sensor values here\n`;
      code += `  display.display();\n`;
      code += `}\n`;
    }
    
    return code;
  }
  
  generateConfigHeader(spec, components) {
    let header = '';
    
    header += `#ifndef CONFIG_H\n`;
    header += `#define CONFIG_H\n\n`;
    
    header += `// System Configuration\n`;
    header += `#define SYSTEM_NAME "${spec.purpose || 'System'}"\n`;
    header += `#define VERSION "1.0.0"\n\n`;
    
    // Pin definitions
    header += `// Pin Definitions\n`;
    header += `#define LED_PIN 2\n`;
    
    // I2C pins (platform specific)
    const platform = this.detectPlatform(components);
    if (platform === 'esp32') {
      header += `#define SDA_PIN 21\n`;
      header += `#define SCL_PIN 22\n`;
    } else {
      header += `#define SDA_PIN SDA\n`;
      header += `#define SCL_PIN SCL\n`;
    }
    
    // Sensor addresses
    header += `\n// I2C Addresses\n`;
    const sensors = components.filter(c => c.component.specs?.type?.includes('sensor'));
    for (const sensor of sensors) {
      const address = this.getSensorI2CAddress(sensor.component.title);
      if (address) {
        const name = sensor.component.title.replace(/[^A-Za-z0-9]/g, '_').toUpperCase();
        header += `#define ${name}_ADDR ${address}\n`;
      }
    }
    
    // Timing constants
    header += `\n// Timing Constants\n`;
    header += `#define SENSOR_READ_INTERVAL 1000  // ms\n`;
    header += `#define DISPLAY_UPDATE_INTERVAL 500  // ms\n`;
    header += `#define SERIAL_BAUD 115200\n\n`;
    
    // Feature flags
    header += `// Feature Flags\n`;
    header += `#define ENABLE_SERIAL_DEBUG 1\n`;
    if (components.some(c => c.component.specs?.type === 'display')) {
      header += `#define ENABLE_DISPLAY 1\n`;
    }
    if (components.some(c => c.component.specs?.wifi)) {
      header += `#define ENABLE_WIFI 1\n`;
    }
    
    header += `\n#endif // CONFIG_H\n`;
    
    return header;
  }
  
  generateLibraryList(components) {
    const libraries = new Set();
    
    // Platform libraries
    libraries.add('Wire (I2C communication)');
    
    // Sensor libraries
    for (const comp of components) {
      const sensorLib = this.getSensorLibrary(comp.component.title);
      if (sensorLib) {
        libraries.add(sensorLib.library.replace('.h', ''));
      }
      
      const displayLib = this.getDisplayLibrary(comp.component.title);
      if (displayLib) {
        libraries.add(displayLib.library.replace('.h', ''));
      }
    }
    
    let content = 'Required Arduino Libraries:\n\n';
    for (const lib of Array.from(libraries).sort()) {
      content += `- ${lib}\n`;
    }
    
    content += '\nInstallation:\n';
    content += 'Open Arduino IDE -> Tools -> Manage Libraries\n';
    content += 'Search for each library name and install the latest version.\n';
    
    return content;
  }
  
  generatePlatformConfig(platform, spec) {
    let config = `[env:${platform}]\n`;
    
    switch (platform) {
      case 'esp32':
        config += `platform = espressif32\n`;
        config += `board = esp32dev\n`;
        config += `framework = arduino\n`;
        config += `monitor_speed = 115200\n`;
        config += `lib_deps = \n`;
        config += `    adafruit/Adafruit BME280 Library\n`;
        config += `    adafruit/Adafruit SSD1306\n`;
        break;
        
      case 'rp2040':
        config += `platform = raspberrypi\n`;
        config += `board = pico\n`;
        config += `framework = arduino\n`;
        config += `monitor_speed = 115200\n`;
        break;
        
      default: // arduino
        config += `platform = atmelavr\n`;
        config += `board = uno\n`;
        config += `framework = arduino\n`;
        config += `monitor_speed = 115200\n`;
        break;
    }
    
    return config;
  }
  
  generateFirmwareReadme(spec, platform, components) {
    let readme = `# ${spec.purpose || 'Firmware Project'}\n\n`;
    
    readme += `Generated firmware for ${platform} platform.\n\n`;
    
    readme += `## Hardware Components\n\n`;
    for (const comp of components) {
      readme += `- ${comp.component.title} (${comp.purpose})\n`;
    }
    
    readme += `\n## Setup Instructions\n\n`;
    readme += `1. Install required libraries (see libraries.txt)\n`;
    readme += `2. Connect hardware according to wiring diagram\n`;
    readme += `3. Upload firmware to ${platform}\n`;
    readme += `4. Open serial monitor at 115200 baud\n\n`;
    
    readme += `## Pin Configuration\n\n`;
    readme += `- I2C SDA: Pin ${platform === 'esp32' ? '21' : 'SDA'}\n`;
    readme += `- I2C SCL: Pin ${platform === 'esp32' ? '22' : 'SCL'}\n`;
    readme += `- Status LED: Pin 2\n\n`;
    
    readme += `## Features\n\n`;
    for (const feature of spec.features || []) {
      readme += `- ${feature}\n`;
    }
    
    readme += `\n## Constraints\n\n`;
    if (spec.constraints) {
      readme += `- Voltage: ${spec.constraints.voltage}\n`;
      readme += `- Power: ${spec.constraints.power}\n`;
      readme += `- Size: ${spec.constraints.size}\n`;
    }
    
    readme += `\nGenerated by Tyton Creation Engine\n`;
    
    return readme;
  }
  
  // Platform-specific templates
  getESP32Setup() {
    return `  // ESP32 specific setup\n  pinMode(LED_BUILTIN, OUTPUT);\n  \n  // Initialize WiFi if needed\n  // WiFi.begin("ssid", "password");\n`;
  }
  
  getESP32Loop() {
    return `  // ESP32 specific loop code\n  digitalWrite(LED_BUILTIN, !digitalRead(LED_BUILTIN)); // Blink LED\n`;
  }
  
  getArduinoSetup() {
    return `  // Arduino specific setup\n  pinMode(LED_BUILTIN, OUTPUT);\n`;
  }
  
  getArduinoLoop() {
    return `  // Arduino specific loop code\n  digitalWrite(LED_BUILTIN, !digitalRead(LED_BUILTIN)); // Blink LED\n`;
  }
  
  getRP2040Setup() {
    return `  // RP2040 specific setup\n  pinMode(LED_BUILTIN, OUTPUT);\n`;
  }
  
  getRP2040Loop() {
    return `  // RP2040 specific loop code\n  digitalWrite(LED_BUILTIN, !digitalRead(LED_BUILTIN)); // Blink LED\n`;
  }
  
  // Helper functions for sensor libraries
  getSensorLibrary(componentTitle) {
    const title = componentTitle.toUpperCase();
    for (const [sensor, lib] of Object.entries(this.sensorLibraries)) {
      if (title.includes(sensor)) {
        return lib;
      }
    }
    return null;
  }
  
  getSensorInit(componentTitle) {
    const lib = this.getSensorLibrary(componentTitle);
    return lib ? lib.init : null;
  }
  
  getSensorSetup(componentTitle) {
    const lib = this.getSensorLibrary(componentTitle);
    return lib ? lib.setup : null;
  }
  
  getSensorRead(componentTitle) {
    const lib = this.getSensorLibrary(componentTitle);
    return lib ? lib.read : null;
  }
  
  getSensorI2CAddress(componentTitle) {
    const title = componentTitle.toUpperCase();
    if (title.includes('BME280')) return '0x76';
    if (title.includes('SCD41')) return '0x62';
    if (title.includes('MPU6050')) return '0x68';
    if (title.includes('SSD1306')) return '0x3C';
    return null;
  }
  
  getDisplayLibrary(componentTitle) {
    const title = componentTitle.toUpperCase();
    for (const [display, lib] of Object.entries(this.displayLibraries)) {
      if (title.includes(display)) {
        return lib;
      }
    }
    return null;
  }
  
  getDisplayInit(componentTitle) {
    const lib = this.getDisplayLibrary(componentTitle);
    return lib ? lib.init : null;
  }
  
  getDisplaySetup(componentTitle) {
    const lib = this.getDisplayLibrary(componentTitle);
    return lib ? lib.setup : null;
  }
  
  countInterfaces(components) {
    const interfaces = new Set();
    for (const comp of components) {
      const specs = comp.component.specs || {};
      if (specs.interface) {
        interfaces.add(specs.interface);
      }
    }
    return interfaces.size;
  }
  
  calculateFirmwareComplexity(components) {
    let complexity = 0;
    
    complexity += components.filter(c => c.component.specs?.type?.includes('sensor')).length * 3;
    complexity += components.filter(c => c.component.specs?.type === 'display').length * 2;
    complexity += components.filter(c => c.component.specs?.wifi).length * 4;
    
    if (complexity < 10) return 'simple';
    if (complexity < 20) return 'moderate';
    return 'complex';
  }
}

module.exports = new FirmwareService();